import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import { IsDefined, IsEmail, IsIn, IsOptional, IsString, Validate } from 'class-validator';
import { IsNumberOrString } from './common/validators/number-or-string.validator';

export class LoginSocialDto {
  @ApiProperty({
    example: 'google',
  })
  @IsString()
  social_provider: string;

  @ApiProperty({
    example: 'b2c',
    description: 'b2b OR b2c',
  })
  @IsString()
  app_type: string;

  @ApiProperty({
    description: 'Access Token Generated by the client side Oauth ',
  })
  @Validate(IsNumberOrString)
  tokenId: string;

  @ApiProperty({
    example: 102,
  })
  @Validate(IsNumberOrString)
  app_id: string;
}

export class ShopListDto {
  @ApiProperty()
  @Validate(IsNumberOrString)
  consultant_company_id: number;
}

export class FetchFwVersionDto {
  @ApiProperty()
  @IsString()
  optic_number: string;
}

export class UpdateFwVersionDto {
  @ApiProperty()
  @IsString()
  optic_number: string;

  @ApiProperty()
  @IsString()
  fw_version: string;
}

export class DecodeWebResultDto {
  @ApiProperty()
  @IsString()
  token: string;
}

export class WebResultBaseDto {
  @ApiPropertyOptional({ description: 'Consultant company ID' })
  @IsOptional()
  @Validate(IsNumberOrString)
  consultant_company_id?: number | string;

  @ApiPropertyOptional({ description: 'Application ID' })
  @IsOptional()
  @Validate(IsNumberOrString)
  app_id?: number | string;

  @ApiPropertyOptional({ description: 'Locale (default: en)' })
  @IsOptional()
  @IsString()
  locale?: string;

  @ApiPropertyOptional({ description: 'Result type for routing' })
  @IsOptional()
  @IsString()
  type?: string;

  @ApiPropertyOptional({ description: 'Analysis type (token payload)' })
  @IsOptional()
  @IsString()
  analysis?: string;

  @ApiPropertyOptional({
    enum: ['legacy', 'integrated'],
    description: 'Analysis server version: legacy for the old server, integrated for the unified server',
    example: 'integrated',
  })
  @IsOptional()
  @IsIn(['legacy', 'integrated'])
  analysis_server_version?: 'legacy' | 'integrated';

  @ApiPropertyOptional({
    enum: ['skin_age', 'health_score'],
    description: 'Exactly one analysis output type to include in the web result token',
    example: 'skin_age',
  })
  @IsOptional()
  @IsIn(['skin_age', 'health_score'])
  analysis_output_type?: 'skin_age' | 'health_score';

  @ApiProperty({ description: 'Analysis batch ID (number or string)', example: 12345 })
  @IsDefined()
  @Validate(IsNumberOrString)
  batchId: number | string;

  @ApiPropertyOptional({ description: 'Customer ID (number or string)', example: 6789 })
  @IsOptional()
  @Validate(IsNumberOrString)
  customer_id?: number | string;

  @ApiPropertyOptional({
    enum: ['chowis', 'choicetech', 'dxself'],
    description: 'Web result base URL',
  })
  @IsOptional()
  @IsIn(['chowis', 'choicetech', 'dxself'])
  webresult_base_url?: 'chowis' | 'choicetech' | 'dxself';
}

export class ShareWebResultDto extends WebResultBaseDto {
  @ApiPropertyOptional({ description: 'Recipient email address' })
  @IsOptional()
  @IsEmail()
  email?: string;
}

export class GenerateQrWebResultDto extends WebResultBaseDto {}
