name: Production Release

on:
  push:
    branches:
      - china_main
  workflow_dispatch:

jobs:
  deploy-china:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.CHINA_SERVER_KEY }}

      - name: Deploy to China Server
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@1.116.243.170 << 'EOF'
            set -e

            APP_DIR="/home/ubuntu/repositories/BE-CNDP-HAIR-v2"

            echo "Move to project directory"
            cd $APP_DIR

            echo "Force sync with origin"
            git fetch origin
            git reset --hard origin/china_main

            echo "Run deployment script"
            bash sync.sh

            echo "China production deployment completed"
          EOF
